# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='talks.TalkList')),
            ],
        ),
    ]
