# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0002_talk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talk',
            options={'ordering': ('when', 'room')},
        ),
        migrations.AddField(
            model_name='talk',
            name='host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='talk',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='talk',
            name='room',
            field=models.CharField(
                blank=True, choices=[('517D', '517D'), ('517C', '517C'), ('517AB', '517AB')], max_length=5),
        ),
        migrations.AddField(
            model_name='talk',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='talk',
            name='when',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='talk',
            unique_together=set([('talk_list', 'name')]),
        ),
    ]
