# pylint: disable=C0103
# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 13:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0003_auto_20170726_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talklist',
            options={'ordering': ('name', )},
        ),
        migrations.AddField(
            model_name='talk',
            name='user',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='talks',
                to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
