# pylint: disable=C0103
# Generated by Django 2.0.2 on 2018-02-27 11:25

from django.db import migrations

import autoslug.fields


class Migration(migrations.Migration):

    dependencies = [
        ('talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
